# docker-compose.yaml for airflow with mysql with airflow server and scheduler running in separate containers

version: "2"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  webserver:
    image: puckel/docker-airflow
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=y
      - EXECUTOR=Celery
    volumes:
      - ./data/airflow:/usr/local/airflow
  scheduler:
    image: puckel/docker-airflow
    restart: always
    depends_on:
      - mysql
    command: scheduler
    environment:
      - LOAD_EX=y
      - EXECUTOR=Celery
    volumes:
      - ./data/airflow:/usr/local/airflow
  flower:
    image: puckel/docker-airflow
    restart: always
    depends_on:
      - mysql
    command: flower
    ports:
      - "5555:5555"
    environment:
      - LOAD_EX=y
      - EXECUTOR=Celery
    volumes:
      - ./data/airflow:/usr/local/airflow
