version: "3"
services:
  webserver:
    build:
      context: ./app/
      dockerfile: DockerFile
    image: puckel/docker-airflow:latest
    container_name: test_container_test
    volumes:
      - /home/ubuntu/dags1/:/usr/local/airflow/dags
    ports:
      - 8080:8080
    networks:
      - backend
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testdb
    container_name: mysql_container_test
    ports:
      - 3306:3306
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
